# Generated by Django 5.0.1 on 2024-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('cleared', 'Cleared'), ('uncleared', 'Uncleared'), ('void', 'Void')], max_length=50),
        ),
    ]
